local map = vim.keymap.set
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
map('n', '<Esc>', '<cmd>nohlsearch<CR>')
map('n', '<Tab>', '<cmd>bnext<CR>')
map('n', '<S-Tab>', '<cmd>bprev<CR>')
map('n', '[d', vim.diagnostic.goto_prev, { desc = 'Go to previous [D]iagnostic message' })
map('n', ']d', vim.diagnostic.goto_next, { desc = 'Go to next [D]iagnostic message' })
map('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })
map('n', '<C-h>', '<C-w><C-h>', { desc = 'Move focus to the left window' })
map('n', '<C-l>', '<C-w><C-l>', { desc = 'Move focus to the right window' })
map('n', '<C-j>', '<C-w><C-j>', { desc = 'Move focus to the lower window' })
map('n', '<C-k>', '<C-w><C-k>', { desc = 'Move focus to the upper window' })
map('n', ';', ':', { desc = 'CMD enter command mode' })
map('i', 'jk', '<ESC>')
map('n', '<F2>', ':%s/<C-r><C-w>/<C-r><C-w>/gI<Left><Left><Left>')
map('n', 'n', 'nzzzv')
map('n', 'N', 'Nzzzv')
map('v', 'J', ":m '>+1<CR>gv=gv")
map('v', 'K', ":m '<-2<CR>gv=gv")
map({ 'n', 'v' }, '<leader>y', [["+y]])
map('n', '<leader>Y', [["+Y]])
map('n', '<C-k>', '<cmd>cnext<CR>zz')
map('n', '<C-j>', '<cmd>cprev<CR>zz')
map('n', '<leader>k', '<cmd>lnext<CR>zz')
map('n', '<leader>j', '<cmd>lprev<CR>zz')
map({ 'n', 'i', 'v' }, '<C-s>', '<ESC><cmd> w <cr>')
map({ 'n', 'v' }, '<leader>qq', '<cmd> qa! <cr>')
map({ 'n', 'v' }, '<C-c>', '<ESC><ESC><ESC>')
map('n', '<leader>x', '<cmd>lua MiniBufremove.delete()<CR>')
map('n', '<F5>', vim.cmd.UndotreeToggle)
map('n', '<F6>', vim.cmd.UndotreeFocus)
map('v', '<leader>=', "<ESC><cmd>lua require('Comment.api').toggle.linewise(vim.fn.visualmode())<CR>")
map('n', 'q', '<nop>')
map('n', '<leader>tw', '<cmd>set wrap!<cr>')
map('n', '<leader>tn', '<cmd>set relativenumber!<cr>')
map('n', '<A-m>', '<cmd>MarkdownPreview<cr>')
