local g = vim.g
local o = vim.opt
g.have_nerd_font = true
g.undotree_CustomUndotreeCmd = 'vertical 40 new'
g.undotree_CustomDiffpanelCmd = 'belowright 12 new'
o.number = true
o.relativenumber = true
o.mouse = 'a'
o.showmode = false
o.clipboard = 'unnamedplus'
o.breakindent = true
o.undofile = true
o.ignorecase = true
o.smartcase = true
o.signcolumn = 'yes'
o.updatetime = 250
o.timeoutlen = 300
o.splitright = true
o.splitbelow = true
o.list = true
o.listchars = { tab = '» ', trail = '·', nbsp = '␣' }
o.inccommand = 'split'
o.cursorline = true
o.scrolloff = 10
o.wrap = false
o.expandtab = true
o.shiftwidth = 4
o.smartindent = true
o.tabstop = 4
o.softtabstop = 4
o.hlsearch = true
o.spelllang = 'en_us'
o.spell = true
